// Code generated by genrec. DO NOT EDIT.
package NovelUpdatesClient

type Genre string

// Genres: Total(35)
const (
	GenreAction        Genre = "8"
	GenreAdult         Genre = "280"
	GenreAdventure     Genre = "13"
	GenreComedy        Genre = "17"
	GenreDrama         Genre = "9"
	GenreEcchi         Genre = "292"
	GenreFantasy       Genre = "5"
	GenreGenderBender  Genre = "168"
	GenreHarem         Genre = "3"
	GenreHistorical    Genre = "330"
	GenreHorror        Genre = "343"
	GenreJosei         Genre = "324"
	GenreMartialArts   Genre = "14"
	GenreMature        Genre = "4"
	GenreMecha         Genre = "10"
	GenreMystery       Genre = "245"
	GenrePsychological Genre = "486"
	GenreRomance       Genre = "15"
	GenreSchoolLife    Genre = "6"
	GenreScifi         Genre = "11"
	GenreSeinen        Genre = "18"
	GenreShoujo        Genre = "157"
	GenreShoujoAi      Genre = "851"
	GenreShounen       Genre = "12"
	GenreShounenAi     Genre = "1692"
	GenreSliceofLife   Genre = "7"
	GenreSmut          Genre = "281"
	GenreSports        Genre = "1357"
	GenreSupernatural  Genre = "16"
	GenreTragedy       Genre = "132"
	GenreWuxia         Genre = "479"
	GenreXianxia       Genre = "480"
	GenreXuanhuan      Genre = "3954"
	GenreYaoi          Genre = "560"
	GenreYuri          Genre = "922"
)

var (
	GenreToName = map[Genre]string{
		GenreAction:        "Action",
		GenreAdult:         "Adult",
		GenreAdventure:     "Adventure",
		GenreComedy:        "Comedy",
		GenreDrama:         "Drama",
		GenreEcchi:         "Ecchi",
		GenreFantasy:       "Fantasy",
		GenreGenderBender:  "Gender Bender",
		GenreHarem:         "Harem",
		GenreHistorical:    "Historical",
		GenreHorror:        "Horror",
		GenreJosei:         "Josei",
		GenreMartialArts:   "Martial Arts",
		GenreMature:        "Mature",
		GenreMecha:         "Mecha",
		GenreMystery:       "Mystery",
		GenrePsychological: "Psychological",
		GenreRomance:       "Romance",
		GenreSchoolLife:    "School Life",
		GenreScifi:         "Sci-fi",
		GenreSeinen:        "Seinen",
		GenreShoujo:        "Shoujo",
		GenreShoujoAi:      "Shoujo Ai",
		GenreShounen:       "Shounen",
		GenreShounenAi:     "Shounen Ai",
		GenreSliceofLife:   "Slice of Life",
		GenreSmut:          "Smut",
		GenreSports:        "Sports",
		GenreSupernatural:  "Supernatural",
		GenreTragedy:       "Tragedy",
		GenreWuxia:         "Wuxia",
		GenreXianxia:       "Xianxia",
		GenreXuanhuan:      "Xuanhuan",
		GenreYaoi:          "Yaoi",
		GenreYuri:          "Yuri",
	}
)

var (
	NameToGenre = map[string]Genre{
		"Action":        GenreAction,
		"Adult":         GenreAdult,
		"Adventure":     GenreAdventure,
		"Comedy":        GenreComedy,
		"Drama":         GenreDrama,
		"Ecchi":         GenreEcchi,
		"Fantasy":       GenreFantasy,
		"Gender Bender": GenreGenderBender,
		"Harem":         GenreHarem,
		"Historical":    GenreHistorical,
		"Horror":        GenreHorror,
		"Josei":         GenreJosei,
		"Martial Arts":  GenreMartialArts,
		"Mature":        GenreMature,
		"Mecha":         GenreMecha,
		"Mystery":       GenreMystery,
		"Psychological": GenrePsychological,
		"Romance":       GenreRomance,
		"School Life":   GenreSchoolLife,
		"Sci-fi":        GenreScifi,
		"Seinen":        GenreSeinen,
		"Shoujo":        GenreShoujo,
		"Shoujo Ai":     GenreShoujoAi,
		"Shounen":       GenreShounen,
		"Shounen Ai":    GenreShounenAi,
		"Slice of Life": GenreSliceofLife,
		"Smut":          GenreSmut,
		"Sports":        GenreSports,
		"Supernatural":  GenreSupernatural,
		"Tragedy":       GenreTragedy,
		"Wuxia":         GenreWuxia,
		"Xianxia":       GenreXianxia,
		"Xuanhuan":      GenreXuanhuan,
		"Yaoi":          GenreYaoi,
		"Yuri":          GenreYuri,
	}
)
